spring.application.name=crypto-agent

openai.api-key=${OPENROUTER_API_KEY}
openai.base-url=https://openrouter.ai/api/v1
openai.model=openai/gpt-oss-20b:free

server.port=8080

logging.level.dev.langchain4j=DEBUG